site_name: QRSpy
pages:
- Home: 'index.md'
- User Guide:
    - 'Summary': 'user-guide/summary.md'
    - 'Connecting to Qlik Sense': 'user-guide/connecting.md'
    - 'Examples': 'user-guide/usage.md'
    - HTTP GET:
      - 'Filtering': 'user-guide/filter.md'
      - 'get about': 'user-guide/get_about.md'
      - 'get app': 'user-guide/get_app.md'
      - 'get appcount': 'user-guide/get_appcount.md'
      - 'get dataconnection': 'user-guide/get_dataconnection.md'
      - 'get lef': 'user-guide/get_lef.md'
      - 'get license': 'user-guide/get_license.md'
      - 'get user': 'user-guide/get_user.md'
      - 'get customproperty': 'user-guide/get_customproperty.md'
      - 'get tag': 'user-guide/get_tag.md'
      - 'get task': 'user-guide/get_task.md'
      - 'get systemrule': 'user-guide/get_systemrule.md'
      - 'get userdirectory': 'user-guide/get_userdirectory.md'
      - 'get extension': 'user-guide/get_extension.md'
      - 'get stream': 'user-guide/get_stream.md'
      - 'get servernode': 'user-guide/get_servernode.md'
      - 'get useraccesstype': 'user-guide/get_useraccesstype.md'
      - 'get loginaccesstype': 'user-guide/get_loginaccesstype.md'
      - 'get appobject': 'user-guide/get_appobject.md'
      - 'get apidescription': 'user-guide/get_apidescription.md'
      - 'export app': 'user-guide/export_app.md'
      - 'get content library': 'user-guide/get_contentlibrary.md'
      - 'get app privileges': 'user-guide/get_appprivileges.md'
      - 'get virtual proxy': 'user-guide/get_virtualproxy.md'
      - 'get system health': 'user-guide/get_health.md'
    - HTTP PUT:
      - 'publish app': 'user-guide/publish_app.md'
      - 'migrate app': 'user-guide/migrate_app.md'
      - 'publish app object': 'user-guide/publish_appobject.md'
      - 'unpublish app object': 'user-guide/unpublish_appobject.md'
      - 'replace app': 'user-guide/replace_app.md'
      - 'Add user to role': 'user-guide/add_usertorole.md'      
    - HTTP POST:
      - 'set license': 'user-guide/set_license.md'
      - 'import users': 'user-guide/import_users.md'
      - 'import tag': 'user-guide/import_tag.md'
      - 'start task': 'user-guide/start_task.md'
      - 'import extension': 'user-guide/import_extension.md'
      - 'copy app': 'user-guide/copy_app.md'
      - 'new stream': 'user-guide/new_stream.md'
      - 'sync user directory': 'user-guide/sync_userdirectory.md'
      - 'export certificates': 'user-guide/export_certificates.md'
      - 'new dataconnection': 'user-guide/new_dataconnection.md'
      - 'import app': 'user-guide/import_app.md'
      - 'import customproperty': 'user-guide/import_customproperty.md'
      - 'import library content': 'user-guide/import_librarycontent.md'
      - 'reload app': 'user-guide/reload_app.md'
      - 'new system rule': 'user-guide/new_systemrule.md'
    - HTTP DELETE:
      - 'delete user': 'user-guide/delete_user.md'
      - 'delete license': 'user-guide/delete_license.md'
      - 'delete app': 'user-guide/delete_app.md'
      - 'delete stream': 'user-guide/delete_stream.md'
      - 'delete tag': 'user-guide/delete_tag.md'
      - 'delete customproperty': 'user-guide/delete_customproperty.md'
      - 'delete user accesstype': 'user-guide/delete_useraccesstype.md'
      - 'delete login accesstype rule': 'user-guide/delete_loginaccesstype.md'
      - 'delete app object': 'user-guide/delete_appobject.md'
      - 'delete library content': 'user-guide/delete_librarycontent.md'
      - 'delete content library': 'user-guide/delete_contentlibrary.md'
      - 'delete user directory and users': 'user-guide/delete_userdirectoryandusers.md'
- About:
  - 'License': 'about/license.md'

theme: readthedocs
